---

- name: Check if java is installed
  ansible.builtin.stat:
    path: /usr/bin/java
  register: java

- name: Install openjdk if java is not found
  ansible.builtin.apt:
    name: default-jdk
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: not java.stat.exists and ansible_os_family == 'Debian'


- name: Install graylog on Ubuntu
  when: ansible_os_family == 'Debian'
  block:
    - name: Install graylog repo
      ansible.builtin.apt:
        deb: "{{ graylog_repo_pkg }}"

    - name: Install graylog runtime
      ansible.builtin.apt:
        name: "{{ graylog_pkgs }}"
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Deploy graylog config
  ansible.builtin.template:
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
    mode: "0644"
    owner: root
    group: root
  when: graylog_conf is defined
  notify: restart graylog

- name: Reload graylog service daemon
  ansible.builtin.systemd:
    daemon-reload: true
  notify:
    - Start graylog
